[project]
name = "simple"
r_version = "4.4"
description = "A simple project to test force_source functionality and compilation dependencies."
repositories = [
    {alias = "posit", url = "https://packagemanager.posit.co/cran/2024-12-16/", force_source = true}
]
dependencies = [
    "cachem",
]