[project]
# NOTE: do not update the lockfile from this project since we're testing whether we can install a non-current package version
name = "archive"
r_version = "4.4"
repositories = [
    { alias = "CRAN", url = "https://cran.r-project.org" },
]
dependencies = [
    "R6",
]