[project]
name = "r-universe"
r_version = "4.4"

dependencies = [
    "osinfo"
]

repositories = [
    {alias = "r-universe", url = "https://a2-ai.r-universe.dev"},
    {alias = "RSPM", url = "https://packagemanager.posit.co/cran/2024-12-04"},
]