[project]
name = "configure-args-example"
r_version = "4.4"

repositories = [
    { alias = "cran", url = "https://cran.r-project.org" }
]

dependencies = [
    { name = "rgl", force_source = true},
]

[project.configure_args]
"rgl" = [
  { os = "macos", args = ["--disable-opengl"] },
]