[project]
name = "multi-repo"
r_version = "4.4"
repositories = [
    {alias = "posit", url = "https://packagemanager.posit.co/cran/2024-12-16/"},
    { alias = "a2-ai", url = "https://a2-ai.github.io/rv-test-snapshot/2024-12-22/" }
]
dependencies = [
    "pkgpub"
]
