[project]
name = "big"
r_version = "4.4"
repositories = [
    { alias = "RSPM", url = "https://packagemanager.posit.co/cran/2024-12-16/" },
]
dependencies = [
    "abind", "acepack", "admiral", "admiral.test", "admiraldev",
    "AER", "akima", "ALEPlot", "almanac", "alphashape3d", "animation",
    "anytime", "ape", "apexcharter", "aplot", "archive", "argonDash",
    "argonR", "arm", "arrayhelpers", "arrow", "arsenal", "asciicast",
    "ash", "AsioHeaders", "askpass", "assertr", "assertthat", "attempt",
    "AUC", "automap", "av", "aws.s3", "aws.signature", "babelmixr2",
    "backports", "badger", "base64enc", "base64url", "batchmeans",
    "batchtools", "bayesplot", "BayesPostEst", "bayestestR", "BB",
    "BBmisc", "bbmle", "bdsmatrix", "beeswarm", "bench", "benchmarkme",
    "benchmarkmeData", "betareg", "BH", "BiasedUrn", "biblio", "bibtex",
    "bigassertr", "bigD", "biglm", "bigreadr", "bindr", "bindrcpp",
    "binGroup", "binom", "binr", "BiocManager", "bit", "bit64", "bitops",
    "blastula", "blob", "blockrand", "blogdown", "bookdown", "boomer",
    "boot", "box", "box.linters", "box.lsp", "boxr", "BradleyTerry2",
    "brew", "brglm", "brglm2", "bridgesampling", "brio", "brms",
    "Brobdingnag", "broom", "broom.helpers", "broom.mixed", "bs4Dash",
    "bsicons", "bslib", "btergm", "bvls", "ca", "cachem", "Cairo",
    "callr", "campsis", "campsismod", "car", "carData", "cards",
    "caret", "caTools", "CBPS", "cellranger", "cem", "changepoint",
    "checkmate", "checkpoint", "chk", "chromote", "chron", "cicerone",
    "Ckmeans.1d.dp", "class", "classInt", "cli", "cliapp", "clinfun",
    "clinPK", "clipr", "clisymbols", "clock", "clue", "cluster",
    "clustermq", "cmprsk", "cobalt", "cobs", "coda", "codetools",
    "coin", "collapse", "collapsibleTree", "collections", "colorspace",
    "colourpicker", "combinat", "common", "commonmark", "CompQuadForm",
    "condMVNorm", "config", "conflicted", "connectwidgets", "conquer",
    "consort", "coro", "corpcor", "corrplot", "corrr", "coveffectsplot",
    "covr", "cowplot", "cpp11", "cpp11armadillo", "cranlogs", "crayon",
    "credentials", "crosstalk", "crul", "csv", "cubature", "cubelyr",
    "Cubist", "curl", "curry", "cvAUC", "cvTools", "cyclocomp", "d3r",
    "d3Tree", "dagitty", "data.table", "data.tree", "datamods", "datawizard",
    "dbarts", "DBI", "DBItest", "dbplyr", "debugme", "decor", "deldir",
    "dendextend", "DEoptim", "DEoptimR", "Deriv", "desc", "DescTools",
    "deSolve", "details", "devtools", "dfidx", "dfoptim", "DHARMa",
    "diagram", "DiagrammeR", "DiagrammeRsvg", "dials", "DiceDesign",
    "dichromat", "diffdf", "diffmatchpatch", "diffobj", "diffviewer",
    "digest", "diptest", "directlabels", "disk.frame", "distill",
    "distributional", "DistributionUtils", "distro", "dittodb", "dlstats",
    "dm", "dmutate", "doBy", "dockerfiler", "docopt", "docxtractr",
    "doFuture", "doMC", "doParallel", "doRNG", "DoseFinding", "dotCall64",
    "dotwhisker", "downlit", "downloader", "dparser", "dplyr", "dragulaR",
    "drake", "drat", "drc", "dreamerr", "DT", "dtplyr", "dtw", "dtwclust",
    "duckdb", "duckplyr", "dygraphs", "e1071", "earth", "ebal", "ECOSolveR",
    "edfReader", "egg", "eha", "ellipse", "ellipsis", "emayili",
    "emmeans", "encode", "english", "enrichwith", "Epi", "epiR",
    "ergm", "esquisse", "estimability", "etm", "evaluate", "evd",
    "Exact", "exactRankTests", "expm", "extraDistr", "extrafont",
    "extrafontdb", "fansi", "farver", "fastDummies", "fastGHQuad",
    "fastICA", "fastmap", "fastmatch", "fastshap", "fauxpas", "fda",
    "fds", "feather", "ff", "fftwtools", "fields", "filehash", "filelock",
    "filesstrings", "fit.models", "fitdistrplus", "fixest", "flexclust",
    "flexdashboard", "flexmix", "flexsurv", "flextable", "FME", "fmtr",
    "FNN", "foghorn", "fontawesome", "fontBitstreamVera", "fontcm",
    "fontLiberation", "fontquiver", "forcats", "foreach", "forecast",
    "foreign", "forestplot", "forge", "formatR", "formattable", "formatters",
    "Formula", "fpc", "fracdiff", "fresh", "fs", "fst", "fstcore",
    "furrr", "futile.logger", "futile.options", "future", "future.apply",
    "future.batchtools", "future.callr", "GA", "gam", "gamlss", "gamlss.data",
    "gamlss.dist", "gamm4", "gap", "gap.datasets", "gargle", "gbm",
    "gbRd", "gclus", "gdata", "gdtools", "gee", "geepack", "geigen",
    "generics", "GenSA", "geometry", "gert", "getPass", "gettz",
    "gfonts", "GGally", "ggalt", "gganimate", "ggbeeswarm", "ggbreak",
    "ggbump", "ggcorrplot", "ggdag", "ggdist", "ggeasy", "ggeffects",
    "ggforce", "ggfortify", "ggfun", "ggh4x", "gghalves", "gghighlight",
    "ggmcmc", "ggnewscale", "ggplot2", "ggplot2movies", "ggplotify",
    "ggPMX", "ggpubr", "ggRandomForests", "ggraph", "ggrepel", "ggridges",
    "ggsci", "ggsignif", "ggstance", "ggstats", "ggsurvfit", "ggtext",
    "ggthemes", "gh", "gifski", "git2r", "gitcreds", "gld", "glmmTMB",
    "glmnet", "glmnetUtils", "globals", "glue", "gmailr", "gmm",
    "gmodels", "gmp", "gnlm", "gnm", "golem", "googledrive", "googlesheets4",
    "gower", "GPArotation", "GPfit", "gplots", "graphlayouts", "gridBase",
    "gridExtra", "gridGraphics", "gridpattern", "gridtext", "gsDesign",
    "gstat", "gt", "gtable", "gtools", "gtsummary", "h2o", "hardhat",
    "harrypotter", "haven", "HDInterval", "hdrcde", "heemod", "here",
    "hexbin", "highlight", "highr", "Hmisc", "hms", "hrbrthemes",
    "htmlTable", "htmltools", "htmlwidgets", "httpcode", "httptest",
    "httpuv", "httr", "httr2", "hunspell", "huxtable", "hydroGOF",
    "hydroTSM", "ids", "igraph", "iml", "imola", "import", "infer",
    "influenceR", "ini", "inline", "insight", "intergraph", "interp",
    "intervals", "inum", "ipaddress", "ipred", "IRdisplay", "IRkernel",
    "irlba", "isoband", "ISwR", "iterators", "itertools", "jagsUI",
    "janitor", "jcolors", "JM", "JMbayes", "joineRML", "jomo", "jose",
    "jpeg", "jquerylib", "jsonlite", "jsTree", "jsTreeR", "jtools",
    "juicyjuice", "JuliaCall", "kableExtra", "Kendall", "keras",
    "kernlab", "KernSmooth", "keyring", "klaR", "km.ci", "KMsurv",
    "knitcitations", "knitr", "ks", "labeling", "labelled", "Lahman",
    "lambda.r", "lambdr", "languageserver", "later", "latex2exp",
    "lattice", "latticeExtra", "lava", "lavaan", "lazyeval", "lbfgs",
    "lbfgsb3c", "leaflet", "leaflet.providers", "leaps", "LearnBayes",
    "learnr", "lemon", "lfe", "lgr", "lhs", "libcoin", "lifecycle",
    "linpk", "linprog", "lintr", "listenv", "listviewer", "lm.beta",
    "lme4", "lmerTest", "lmodel2", "lmom", "lmtest", "lobstr", "locatexec",
    "locfit", "log4r", "logger", "logitnorm", "logr", "loo", "lotri",
    "lpSolve", "lpSolveAPI", "lsei", "lsmeans", "lubridate", "madness",
    "magic", "magick", "magrittr", "maketools", "manipulateWidget",
    "mapbayr", "mapdata", "mapproj", "maps", "margins", "markdown",
    "markovchain", "MASS", "Matching", "MatchIt", "mathjaxr", "Matrix",
    "matrixcalc", "MatrixModels", "matrixStats", "maxLik", "maxstat",
    "mc2d", "mclogit", "mclust", "mcmc", "MCMCpack", "mcmcse", "mda",
    "mediation", "mefa", "memisc", "memoise", "metadat", "metafor",
    "metaplot", "Metrics", "mets", "mfx", "mgcv", "mi", "mice", "microbenchmark",
    "mime", "miniCRAN", "miniUI", "minpack.lm", "minqa", "misaem",
    "misc3d", "miscTools", "mitml", "mitools", "mix", "mlbench",
    "mlogit", "mlr", "mlr3", "mlr3measures", "mlr3misc", "mlxR",
    "mmrm", "mnormt", "MNP", "mockery", "mockr", "modeldata", "modelenv",
    "ModelMetrics", "modelr", "modeltests", "modeltools", "moments",
    "monaco", "monolix2rx", "mrgsim.parallel", "mrgsim.sa", "mrgsolve",
    "msm", "mstate", "muhaz", "multcomp", "multicool", "munsell",
    "mvnfast", "mvtnorm", "n1qn1", "naniar", "nanoarrow", "nanoparquet",
    "nanotime", "narray", "ncappc", "ncar", "ndjson", "neldermead",
    "network", "networkD3", "neuralnet", "nleqslv", "nlme", "nlmixr2",
    "nlmixr2data", "nlmixr2est", "nlmixr2extra", "nlmixr2lib", "nlmixr2plot",
    "nloptr", "NMcalc", "NMdata", "NMsim", "nnet", "nnls",
    "NonCompart", "nonmem2R", "nonmem2rx", "nonmemica", "norm", "npde",
    "npsurv", "numbers", "numDeriv", "nycflights13", "oaqc", "odbc",
    "officedown", "officer", "omsvg", "oompaBase", "openmetrics",
    "openssl", "openxlsx", "optextras", "optimbase", "optimsimplex",
    "optimx", "optmatch", "optweight", "ordinal", "orientlib", "osqp",
    "packer", "packrat", "padr", "pagedown", "pagenum", "pak", "paletteer",
    "palmerpenguins", "palr", "pals", "pamr", "pan", "pander", "paradox",
    "parallelly", "parallelMap", "parameters", "ParamHelpers", "parsedate",
    "parsnip", "partitions", "party", "partykit", "patchwork", "paws",
    "paws.analytics", "paws.application.integration", "paws.common",
    "paws.compute", "paws.cost.management", "paws.customer.engagement",
    "paws.database", "paws.developer.tools", "paws.end.user.computing",
    "paws.machine.learning", "paws.management", "paws.networking",
    "paws.security.identity", "paws.storage", "pbapply", "pbdZMQ",
    "pbivnorm", "pbkrtest", "pcaPP", "pdftools", "pec", "PEIP", "performance",
    "PerformanceAnalytics", "permute", "PFIM", "pharmaRTF", "pharmaversesdtm",
    "phosphoricons", "pillar", "pingr", "pinp", "pins", "PK", "pkgbuild",
    "pkgcache", "pkgconfig", "pkgdepends", "pkgdown", "pkgKitten",
    "pkgload", "pkgnet", "PKI", "PKNCA", "pkr", "plm", "plogr", "plot3D",
    "plotly", "plotlyGeoAssets", "plotmo", "plotrix", "pls", "plumber",
    "plyr", "pmxTools", "png", "pointblank", "poLCA", "polspline",
    "polyclip", "polynom", "pool", "PopED", "posterior", "PowerTOST",
    "prabclus", "pracma", "praise", "PreciseSums", "precommit", "prediction",
    "prettycode", "prettydoc", "prettyunits", "prismatic", "pROC",
    "processx", "prodlim", "proffer", "profile", "profileModel",
    "profmem", "profvis", "progress", "progressr", "proj4", "projpred",
    "promises", "prompt", "PropCIs", "proto", "protolite", "proxy",
    "PRROC", "pryr", "ps", "psych", "Publish", "purrr", "pwr", "pzfx",
    "qap", "qdapRegex", "qgam", "qpdf", "qpNCA", "qrnn", "qs", "quadprog",
    "quantmod", "quantreg", "quarto", "questionr", "QuickJSR", "qvcalc",
    "qwraps2", "R.cache", "R.methodsS3", "R.oo", "R.rsp", "R.utils",
    "r2d3", "R2HTML", "R2jags", "r2rtf", "R2WinBUGS", "R6", "ragg",
    "rainbow", "randomForest", "randomForestSRC", "randtoolbox",
    "ranger", "RANN", "RApiDatetime", "RApiSerialize", "rappdirs",
    "rapportools", "raster", "rbenchmark", "RBesT", "rbibutils",
    "rcartocolor", "Rchoice", "rclipboard", "rcmdcheck", "RColorBrewer",
    "Rcpp", "RcppArmadillo", "RcppCCTZ", "RcppClock", "RcppDate",
    "RcppDE", "RcppEigen", "RcppGSL", "RcppParallel", "RcppProgress",
    "RcppRoll", "RcppThread", "RcppTOML", "RcppZiggurat", "rcrossref",
    "Rcsdp", "RCurl", "Rdpack", "reactable", "reactablefmtr", "reactlog",
    "reactR", "ReacTran", "readr", "readxl", "recipes", "reda", "RefManageR",
    "reformulas", "registry", "relimp", "rem", "rematch", "rematch2",
    "remotes", "renv", "reporter", "repr", "reprex", "repurrrsive",
    "reReg", "reshape", "reshape2", "reticulate", "revealjs", "rex",
    "Rfast", "rgenoud", "rgexf", "rgl", "Rglpk", "rhandsontable",
    "rhino", "RhpcBLASctl", "rhub", "rintrojs", "rio", "riskmetric",
    "riskRegression", "RItools", "rjags", "rJava", "rjson", "RJSONIO",
    "rlang", "rle", "rlecuyer", "rlemon", "RMariaDB", "rmarkdown",
    "rmdformats", "Rmisc", "Rmpfr", "rmutil", "RMySQL", "rnaturalearth",
    "rngtools", "rngWELL", "robust", "robustbase", "ROCR", "RODBC",
    "ROI", "ROI.plugin.glpk", "Rook", "rootSolve", "roxygen2", "rpart",
    "rpart.plot", "RPMG", "RPostgres", "RPostgreSQL", "rprintf",
    "rprojroot", "RProtoBuf", "rpsftm", "rrcov", "rsample", "rsconnect",
    "rscontract", "RSEIS", "RSiena", "Rsmlx", "Rsolnp", "RSpectra",
    "RSQLite", "RsSimulx", "rstan", "rstanarm", "rstanemax", "rstantools",
    "rstatix", "rstpm2", "rstudioapi", "rsvg", "rtables", "rtf",
    "rticles", "Rttf2pt1", "RUnit", "runjags", "Runuran", "rvcheck",
    "rversions", "rvest", "rvg", "Rwave", "rxode2", "rxode2ll", "rzmq",
    "s2", "saemix", "sandwich", "sas7bdat", "SAScii", "sass", "scagnostics",
    "scales", "scam", "scaRabee", "scatterplot3d", "scico", "scs",
    "secretbase", "selectr", "sem", "semver", "sensitivity", "sensobol",
    "seriation", "servr", "sessioninfo", "sets", "sever", "sf", "sfd",
    "sfsmisc", "sftime", "shape", "shapr", "shiny", "shiny.react",
    "shiny.router", "shinyAce", "shinyauthr", "shinyBS", "shinybusy",
    "shinycssloaders", "shinydashboard", "shinydashboardPlus", "shinydisconnect",
    "shinyEffects", "shinyFeedback", "shinyFiles", "shinyglide",
    "shinyjqui", "shinyjs", "shinylogs", "shinymeta", "shinyMobile",
    "shinymodels", "shinySelect", "shinystan", "shinytest", "shinytest2",
    "shinythemes", "shinytitle", "shinyvalidate", "shinyWidgets",
    "showimage", "showtext", "showtextdb", "simPH", "sinew", "sitmo",
    "sjlabelled", "skimr", "slackr", "slam", "slickR", "slider",
    "sm", "smoothHR", "sna", "snakecase", "sodium", "som", "sortable",
    "sos", "sourcetools", "sp", "spacetime", "spam", "spaMM", "sparkline",
    "sparklyr", "SparseM", "spatialreg", "spData", "spdep", "spec",
    "speedglm", "spelling", "splines2", "spls", "SQUAREM", "StanHeaders",
    "stargazer", "stars", "starwarsdb", "statmod", "statnet.common",
    "storr", "strex", "stringdist", "stringfish", "stringi", "stringmagic",
    "stringr", "strucchange", "styler", "summarytools", "SuperLearner",
    "superpc", "survey", "survival", "survivalROC", "survminer",
    "survMisc", "svd", "svglite", "svgPanZoom", "svUnit", "swagger",
    "symengine", "sys", "sysfonts", "systemfit", "systemfonts", "table1",
    "tableone", "tables", "tabulapdf", "tarchetypes", "targets",
    "TeachingDemos", "tensorA", "tensorflow", "tern", "terra", "tesseract",
    "testit", "testthat", "testthis", "texPreview", "texreg", "textshaping",
    "tfautograph", "tfruns", "TH.data", "thematic", "threejs", "tibble",
    "tictoc", "tidybayes", "tidycat", "tidycmprsk", "tidygraph",
    "tidylog", "tidymodels", "tidyposterior", "tidyr", "tidyselect",
    "tidytlg", "tidyverse", "tidyvpc", "tikzDevice", "timechange",
    "timeDate", "timereg", "tinytest", "tinytex", "tippy", "TMB",
    "tmvnsim", "tmvtnorm", "tnet", "toastui", "Tplyr", "tracee",
    "transformr", "triebeard", "trimcluster", "tripack", "truncdist",
    "truncnorm", "trust", "tseries", "TSP", "ttdo", "TTR", "tufte",
    "tune", "twang", "tweenr", "txtplot", "txtq", "tzdb", "ucminf",
    "udunits2", "units", "UpSetR", "urca", "urlchecker", "urltools",
    "usethis", "utf8", "uuid", "V8", "vars", "vaultr", "vcd", "vcr",
    "vctrs", "vdiffr", "vegan", "vegawidget", "vioplot", "vipor",
    "viridis", "viridisLite", "visdat", "visNetwork", "vpc", "vroom",
    "waiter", "waldo", "warp", "webdriver", "webfakes", "webmockr",
    "webp", "webshot", "webshot2", "websocket", "webutils", "WeightIt",
    "whereami", "whisker", "whoami", "withr", "wk", "workflows",
    "workflowsets", "writexl", "xaringan", "xaringanthemer", "xergm.common",
    "xfun", "xgboost", "xgxr", "XLConnect", "xlsx", "xlsxjars", "XML",
    "xml2", "xmlparsedata", "xopen", "xpose", "xpose4", "xslt", "xtable",
    "xts", "yaImpute", "yaml", "yamlme", "yardstick", "ymlthis",
    "yulab.utils", "zeallot", "zip", "zoo"
]
