
[project]
name = "rspm"
r_version = "4.4"

repositories = [
    { alias = "RSPM", url = "https://packagemanager.posit.co/cran/latest/" },
    { alias = "CRAN", url = "https://cran.r-project.org" },
]

dependencies = [
    "R6",
    {name = "renv", repository = "CRAN"}
]