name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, linux-musl, macos, windows]
        include:
          - build: linux
            os: ubuntu-22.04
            rust: stable
          - build: linux-musl
            os: ubuntu-22.04
            rust: stable
            target: x86_64-unknown-linux-musl
          - build: macos
            os: macOS-latest
            rust: stable
          - build: windows
            os: windows-2022
            rust: stable
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y musl-tools musl-dev
          rustup target add x86_64-unknown-linux-musl

      - name: Build System Info
        run: rustc --version

      - name: check formatting
        if: matrix.target != 'x86_64-unknown-linux-musl'
        run: cargo fmt --check

      - name: check with all features enabled
        if: matrix.target != 'x86_64-unknown-linux-musl'
        run: |
          cargo check
          cargo check --all-features

      - name: check with all features enabled (musl)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: cargo check --all-features --target x86_64-unknown-linux-musl

      - name: run tests
        if: matrix.target != 'x86_64-unknown-linux-musl'
        run: cargo test --all-features

  integration:
    name: integration-test
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-22.04
            rust: stable
          - build: macos
            os: macOS-latest
            rust: stable
          - build: windows
            os: windows-2022
            rust: stable
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH with repository-specific key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          # ssh key that can only be used to get the repo in example_projects/private-git-dep
          ssh-private-key: ${{ secrets.INTERNAL_SSH_KEY }}

      - name: Add GitHub to known_hosts
        shell: bash
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build System Info
        run: rustc --version
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.2"
      - name: Check R on Windows
        if: runner.os == 'Windows'
        run: |
          echo "C:\R\bin" >> $env:GITHUB_PATH
          Get-ChildItem -Path "C:\R\bin" -Force
          R.exe --version
      - name: Make sure libcurl is installed
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      - name: build binary
        run: |
          cargo build --all-features --release
      - name: run rv sync on all example projects
        run: python .github/scripts/integration.py

  e2e:
    name: e2e-test
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # - name: Set up SSH with repository-specific key
      #   uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #     ssh-private-key: ${{ secrets.INTERNAL_SSH_KEY }}

      # - name: Add GitHub to known_hosts
      #   run: |
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build System Info
        run: rustc --version

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.2"

      - name: build binary
        run: |
          cargo build --all-features --release

      - name: run rv e2e tests
        run: python .github/scripts/e2e.py
